spring:
  main:
    allow-circular-references: true
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/migration/db.changelog.yaml
  feign:
    client:
      config:
        default:
          connectTimeout: 10
          readTimeout: 10
external-service:
  url: http://unavailable000999.ru